# Generated by Django 4.2.1 on 2023-05-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='week_day',
            field=models.IntegerField(default=3),
        ),
    ]
